version: "3.8"
services:
  db:
    container_name: "go-out-db"
    image: "postgres:latest"
    environment:
      POSTGRES_DB: go-out-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  lgtm:
    image: grafana/otel-lgtm
    ports:
      - "4317:4317"
      - "4318:4318"
      - "3000:3000"
